apiVersion: v1
kind: PersistentVolume
metadata:
  name: keycloak-postgres-volume
  namespace: oxid-gateway
  labels:
    type: local
    app: keycloak-postgres
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/postgresql
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-postgres-secret
  namespace: oxid-gateway
  labels:
    app: keycloak-postgres
data:
  POSTGRES_DB: keycloak
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: admin
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-postgres-volume-claim
  namespace: oxid-gateway
  labels:
    app: keycloak-postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-postgres
  namespace: oxid-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak-postgres
  template:
    metadata:
      labels:
        app: keycloak-postgres
    spec:
      containers:
        - name: keycloak-postgres
          image: 'postgres:14'
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: keycloak-postgres-secret
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresdata
      volumes:
        - name: postgresdata
          persistentVolumeClaim:
            claimName: keycloak-postgres-volume-claim
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-postgres
  namespace: oxid-gateway
  labels:
    app: keycloak-postgres
spec:
  type: NodePort
  ports:
    - port: 5432
  selector:
    app: keycloak-postgres
